// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace HamzaTestAPP.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using HamzaTestAPP;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using HamzaTestAPP.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
using HamzaTestAPP.Data;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/Index")]
    public partial class Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 122 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
       

    Customer customer = new Customer();
    List<Customer> customers = new List<Customer>();

    private void GetCustomers()
    {
        customers = customerRepository.GetsCustomers();
    }

    protected override async Task OnInitializedAsync()
    {
        GetCustomers();
    }

    private void Save()

    {
        customerRepository.Save( customer);
        Reset();
        GetCustomers();
    }
    private void Update()

    {
        customerRepository.Update(customer);
        Reset();
        GetCustomers();
    }
    private void Reset()
    {
        Customer customer = new Customer();
    }
    private void Edit (string customerId)
    {
        customer = customerRepository.GetCustomer(customerId);
    }
    private void Delete (string customerId)
    {
        customerRepository.Delete(customerId);
        GetCustomers();
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private HamzaTestAPP.IRepository.ICustomerRepository customerRepository { get; set; }
    }
}
#pragma warning restore 1591
