#pragma checksum "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "d65e5993a9872acf1af3bd1710dab90150c4501b"
// <auto-generated/>
#pragma warning disable 1591
namespace HamzaTestAPP.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Authorization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using HamzaTestAPP;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\_Imports.razor"
using HamzaTestAPP.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
using HamzaTestAPP.Data;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/Index")]
    public partial class Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "class", "row");
            __builder.OpenElement(2, "div");
            __builder.AddAttribute(3, "class", "col-md-4");
            __builder.OpenElement(4, "div");
            __builder.AddAttribute(5, "class", "row");
            __builder.AddMarkupContent(6, "<div class=\"col-md-4\"><label> First Name :</label></div>\r\n            ");
            __builder.OpenElement(7, "div");
            __builder.AddAttribute(8, "class", "col-md-8");
            __builder.OpenElement(9, "input");
            __builder.AddAttribute(10, "style", "width:100%");
            __builder.AddAttribute(11, "placeholder", "First Name");
            __builder.AddAttribute(12, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 12 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.FirstName

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(13, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.FirstName = __value, customer.FirstName));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(14, "\r\n        ");
            __builder.OpenElement(15, "div");
            __builder.AddAttribute(16, "class", "row");
            __builder.AddMarkupContent(17, "<div class=\"col-md-4\"><label> Last Name :</label></div>\r\n            ");
            __builder.OpenElement(18, "div");
            __builder.AddAttribute(19, "class", "col-md-8");
            __builder.OpenElement(20, "input");
            __builder.AddAttribute(21, "style", "width:100%");
            __builder.AddAttribute(22, "placeholder", "Last Name");
            __builder.AddAttribute(23, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 20 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.LastName

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(24, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.LastName = __value, customer.LastName));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(25, "\r\n        ");
            __builder.OpenElement(26, "div");
            __builder.AddAttribute(27, "class", "row");
            __builder.AddMarkupContent(28, "<div class=\"col-md-4\"><label> Phone :</label></div>\r\n            ");
            __builder.OpenElement(29, "div");
            __builder.AddAttribute(30, "class", "col-md-8");
            __builder.OpenElement(31, "input");
            __builder.AddAttribute(32, "style", "width:100%");
            __builder.AddAttribute(33, "placeholder", "Phone");
            __builder.AddAttribute(34, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 28 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.Phone

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(35, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.Phone = __value, customer.Phone));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(36, "\r\n        ");
            __builder.OpenElement(37, "div");
            __builder.AddAttribute(38, "class", "row");
            __builder.AddMarkupContent(39, "<div class=\"col-md-4\"><label> Phone1 :</label></div>\r\n            ");
            __builder.OpenElement(40, "div");
            __builder.AddAttribute(41, "class", "col-md-8");
            __builder.OpenElement(42, "input");
            __builder.AddAttribute(43, "style", "width:100%");
            __builder.AddAttribute(44, "placeholder", "Phone1");
            __builder.AddAttribute(45, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 36 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.Phone1

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(46, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.Phone1 = __value, customer.Phone1));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(47, "\r\n        ");
            __builder.OpenElement(48, "div");
            __builder.AddAttribute(49, "class", "row");
            __builder.AddMarkupContent(50, "<div class=\"col-md-4\"><label> adress :</label></div>\r\n            ");
            __builder.OpenElement(51, "div");
            __builder.AddAttribute(52, "class", "col-md-8");
            __builder.OpenElement(53, "input");
            __builder.AddAttribute(54, "style", "width:100%");
            __builder.AddAttribute(55, "placeholder", "Adress");
            __builder.AddAttribute(56, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 44 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.adress

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(57, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.adress = __value, customer.adress));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(58, "\r\n        ");
            __builder.OpenElement(59, "div");
            __builder.AddAttribute(60, "class", "row");
            __builder.AddMarkupContent(61, "<div class=\"col-md-4\"><label> street :</label></div>\r\n            ");
            __builder.OpenElement(62, "div");
            __builder.AddAttribute(63, "class", "col-md-8");
            __builder.OpenElement(64, "input");
            __builder.AddAttribute(65, "style", "width:100%");
            __builder.AddAttribute(66, "placeholder", "street");
            __builder.AddAttribute(67, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 52 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.street

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(68, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.street = __value, customer.street));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(69, "\r\n        ");
            __builder.OpenElement(70, "div");
            __builder.AddAttribute(71, "class", "row");
            __builder.AddMarkupContent(72, "<div class=\"col-md-4\"><label>Code :</label></div>\r\n            ");
            __builder.OpenElement(73, "div");
            __builder.AddAttribute(74, "class", "col-md-8");
            __builder.OpenElement(75, "input");
            __builder.AddAttribute(76, "style", "width:100%");
            __builder.AddAttribute(77, "placeholder", " Code");
            __builder.AddAttribute(78, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 60 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.PostalCode

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(79, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.PostalCode = __value, customer.PostalCode));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(80, "\r\n        ");
            __builder.OpenElement(81, "div");
            __builder.AddAttribute(82, "class", "row");
            __builder.AddMarkupContent(83, "<div class=\"col-md-4\"><label>HouseNumber:</label></div>\r\n            ");
            __builder.OpenElement(84, "div");
            __builder.AddAttribute(85, "class", "col-md-8");
            __builder.OpenElement(86, "input");
            __builder.AddAttribute(87, "style", "width:100%");
            __builder.AddAttribute(88, "placeholder", "HouseNumber");
            __builder.AddAttribute(89, "value", Microsoft.AspNetCore.Components.BindConverter.FormatValue(
#nullable restore
#line 68 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                              customer.HouseNumber

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(90, "onchange", Microsoft.AspNetCore.Components.EventCallback.Factory.CreateBinder(this, __value => customer.HouseNumber = __value, customer.HouseNumber));
            __builder.SetUpdatesAttributeName("value");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(91, "\r\n        \r\n        ");
            __builder.OpenElement(92, "div");
            __builder.AddAttribute(93, "class", "row");
            __builder.AddMarkupContent(94, "<div class=\"col-md-4\"></div>\r\n            ");
            __builder.OpenElement(95, "div");
            __builder.AddAttribute(96, "class", "col-md-8");
            __builder.OpenElement(97, "button");
            __builder.AddAttribute(98, "class", "btn btn-primary");
            __builder.AddAttribute(99, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 75 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                                                            e => Save()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(100, "Save");
            __builder.CloseElement();
            __builder.AddMarkupContent(101, "\r\n                ");
            __builder.OpenElement(102, "button");
            __builder.AddAttribute(103, "class", "btn btn-danger");
            __builder.AddAttribute(104, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 76 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                                                           e => Reset()

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(105, "style", "float:right;");
            __builder.AddContent(106, "Reset");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(107, "\r\n    ");
            __builder.OpenElement(108, "div");
            __builder.AddAttribute(109, "class", "col-md-8");
            __builder.OpenElement(110, "table");
            __builder.AddAttribute(111, "class", "table table-striped table-bordered");
            __builder.AddMarkupContent(112, @"<thead><tr><th>CustomerId</th>
                    <th>FirstName</th>
                    <th>LastName</th>
                    <th>Phone</th>
                    <th>Phone1</th>
                    <th>adress</th>
                    <th>street</th>
                    <th>Code</th>
                    <th>HouseN</th></tr></thead>
            ");
            __builder.OpenElement(113, "tbody");
#nullable restore
#line 96 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                 if(customers.Count()>0)
            {
                    

#line default
#line hidden
#nullable disable
#nullable restore
#line 98 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                     foreach (var cu in customers)
                {

#line default
#line hidden
#nullable disable
            __builder.OpenElement(114, "tr");
            __builder.OpenElement(115, "td");
            __builder.AddContent(116, 
#nullable restore
#line 101 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.CustomerId

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(117, "\r\n                    ");
            __builder.OpenElement(118, "td");
            __builder.AddContent(119, 
#nullable restore
#line 102 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.FirstName

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(120, "\r\n                    ");
            __builder.OpenElement(121, "td");
            __builder.AddContent(122, 
#nullable restore
#line 103 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.LastName

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(123, "\r\n                    ");
            __builder.OpenElement(124, "td");
            __builder.AddContent(125, 
#nullable restore
#line 104 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.Phone

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(126, "\r\n                    ");
            __builder.OpenElement(127, "td");
            __builder.AddContent(128, 
#nullable restore
#line 105 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.Phone1

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(129, "\r\n                    ");
            __builder.OpenElement(130, "td");
            __builder.AddContent(131, 
#nullable restore
#line 106 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.adress

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(132, "\r\n                    ");
            __builder.OpenElement(133, "td");
            __builder.AddContent(134, 
#nullable restore
#line 107 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.street

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(135, "\r\n                    ");
            __builder.OpenElement(136, "td");
            __builder.AddContent(137, 
#nullable restore
#line 108 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.PostalCode

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(138, "\r\n                    ");
            __builder.OpenElement(139, "td");
            __builder.AddContent(140, 
#nullable restore
#line 109 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                         cu.HouseNumber

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(141, "\r\n                    ");
            __builder.OpenElement(142, "td");
            __builder.OpenElement(143, "button");
            __builder.AddAttribute(144, "class", "btn btn-primary");
            __builder.AddAttribute(145, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 111 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                                                                    e => Edit(@cu.CustomerId)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(146, "Update");
            __builder.CloseElement();
            __builder.AddMarkupContent(147, "\r\n                        ");
            __builder.OpenElement(148, "button");
            __builder.AddAttribute(149, "class", "btn btn-danger");
            __builder.AddAttribute(150, "onclick", Microsoft.AspNetCore.Components.EventCallback.Factory.Create<Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line 112 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                                                                   e => Delete(@cu.CustomerId)

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(151, "Delete");
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line 115 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                }

#line default
#line hidden
#nullable disable
#nullable restore
#line 115 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
                 
            }

#line default
#line hidden
#nullable disable
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line 122 "C:\Users\hp\source\repos\HamzaTestAPP\HamzaTestAPP\Pages\Index.razor"
       

    Customer customer = new Customer();
    List<Customer> customers = new List<Customer>();

    private void GetCustomers()
    {
        customers = customerRepository.GetsCustomers();
    }

    protected override async Task OnInitializedAsync()
    {
        GetCustomers();
    }

    private void Save()

    {
        customerRepository.Save( customer);
        Reset();
        GetCustomers();
    }
    private void Update()

    {
        customerRepository.Update(customer);
        Reset();
        GetCustomers();
    }
    private void Reset()
    {
        Customer customer = new Customer();
    }
    private void Edit (string customerId)
    {
        customer = customerRepository.GetCustomer(customerId);
    }
    private void Delete (string customerId)
    {
        customerRepository.Delete(customerId);
        GetCustomers();
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private HamzaTestAPP.IRepository.ICustomerRepository customerRepository { get; set; }
    }
}
#pragma warning restore 1591
